### ISSUE TITLE
Section principale avec les cartes

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#140]
Les cartes doivent rediriger vers le file repository avec un filtre pour l'étude en question

### DEFECTS
Voir commentaire de Lucas plus bas

**Comment by luclemo** [comment]
@kjacqueschu 

**Couleurs**
- Ce n'est pas le bon jaune dans l'entête des cartes (ça devrait être le même que celui des pilules requête)

**Layout**
Vue qu'on a peu de données, les cartes semblent trop écartées sur les grands écrans. On peut ajuster:
- `.studies-cards .cards-container { repeat(auto-fill,minmax(300px,1fr)) }`
- Supprime le `max-width: 300px;` de `.studies-cards .cards-container`

On devrait obtenir ceci:

![Pasted_Image_2020-12-01__3_00_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/07d51d06-eacc-4af2-8a7d-1ce23006d243)

**Comment by denis-crsj** [comment]
les defects ont été corrigés
