### ISSUE TITLE
 L'icône pour fermer la barre de facette lorsqu'elle est ouverte n'est pas le bon

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#145]
https://www.figma.com/file/hwQfsKv3nw3Kj95WtjfoYS/CQDG---Portail?node-id=774%3A23933

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/1a3c2d27-332d-4f14-b846-ab8ed4227bf0)

**Comment by francisl** [comment]
Nous n'avons pas cette icon actuellement.
@denis-crsj on ferme ou attend le refactor post 8 dec?
