### ISSUE TITLE
Remove container for search box in sidepanel (donors tab)

### ISSUE THREAD

**Issue by francisl** [Ferlab-Ste-Justine/cqdg-project#148]
### DEFECTS
- [x] Le container a été retiré pour l'onglet "Fichier" mais est toujours présent pour l'onglet "Donneurs"

**Comment by denis-crsj** [comment]
@francisl Le container a été retiré pour l'onglet "Fichier" mais semble toujours être présent pour l'onglet "Donneurs"

**Comment by denis-crsj** [comment]
Corrigé
