### ISSUE TITLE
Répertoire de fichiers - Checkbox background color

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#151]
The color for the background of the checkboxes is wrong. It should be #008FC7

**Comment by kjacqueschu** [comment]
@denis-crsj ceci demande de recréer le checkbox qui existe par défaut dans le browser. ANt-Design vient avec le custom checkbox qu'on va pouvoir utiliser après le 8 décembre et styler de la bonne couleurs :). sinon je dois le refaire custom alors qu'il vient de base avec ant

**Comment by denis-crsj** [comment]
@kjacqueschu Ok cool on laisse comme ca alors ! Je ferme la carte.
