### ISSUE TITLE
Query Builder: i18n

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/cqdg-project#157]
[] Le nom des champs dans la requête devrait être en français sur la page en français

[] Nom des champs: En francais, ne jamais mettre la première lettre en majuscule sauf pour le premier mot. Ex Données harmonisées et non pas Données Harmonisées.
En anglais, on met des majuscules pour chaque mot

[] Stratégie expérimentale et non pas Stratégie experimental

[] short_name_keyword : Quand on recherche par nom d’étude, le nom du champ devrait être Étude

**Comment by denis-crsj** [comment]
Tout fixé.
