### ISSUE TITLE
CQDG-DOCS - Mettre à jour les gabarits de fichiers

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/cqdg-project#163]
Les gabarits se trouvent dans : cqdg-docs/scripts/dictionary/schemas/example_files.  
Enlever les reliques de ICGC-Argo et remplacer par les fichiers fournis par Catherine.

**Comment by denis-crsj** [comment]
Tous les templates ton là lors du téléchargement
