### ISSUE TITLE
Page entité fichiers

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/cqdg-project#198]
Analyse en cours
https://www.notion.so/ferlab/Page-entit-Fichier-ed9d06e4766e45418cc2c80b4f0c2d23

**Comment by plaplante-chust** [comment]
Besoin du modèle de métadonnées pour les fichiers.

**Comment by denis-crsj** [comment]
Priorité à la page entité Étude, la page entité donneur et la page entité Fichier peuvent attendre un peu. Je ferme cette carte pour l'instant.
