### ISSUE TITLE
Session de travail: gestion des ACLs au niveau du sample

### ISSUE THREAD

**Issue by plaplante-lab** [Ferlab-Ste-Justine/cqdg-project#201]
Développement d'un répertoire de chercheurs (oauth provider)?
Connexion à keycloak via Service Provider Interfaces?
Definir a quel(s) niveau(x) on veut gérer les ACLs? 

Avant de se lancer dans le dev d'un truc custom, Keycloak semble supporter un modèle très poussé.  Je crois qu'un spike s'impose: https://www.keycloak.org/docs/latest/authorization_services

GA4GH
https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md

https://vimeo.com/378875784
mdp: precinomics

**Comment by plaplante-chust** [comment]
Tel que discuté avec Catherine, contrôle d'accès par fichier par utilisateur.
Un utilisateur fait une *demande d'accès* pour une liste de fichiers donnée.  Sur approbation, l'utilisateur aura accès aux fichiers pour une période de temps.  Donc, on doit gérer l'expiration des accès.

Conditions d'utilisation PAR ÉTUDE.  Est-ce qu'on aura besoin d'un système de "Enterprise consent and preference management"?
