### ISSUE TITLE
File repository - Rendre les infos du tableau cliquables

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#277]
Il faut faire que les informations dans le tableau comme le nombre de participants, le format de fichier, etc... soient cliquables et permettent de metre à jour la requête et les graphiques

**Comment by kjacqueschu** [comment]
La base pour les liens été mise en place. il manque de l'information côté arranger pour terminer la tâche.
Par exemple: on doit pouvoir faire une aggregation des catégories de fichiers par étude.
