### ISSUE TITLE
Expiration du token authentification

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/cqdg-project#286]
Quel est le comportement souhaité?  On reste connecté à jamais?  La connexion expire après 1 journée ou 1 heure d'inactivité?  Lorsque le token expire, est-ce qu'on présente une modale pour informer l'utilisateur que sa session a expirée ou est-ce qu'on redirige sur la page de login directement?  Maquettes et textes pour la modale si applicable.

cc: @denis-crsj @luclemo @kjacqueschu

**Comment by luclemo** [comment]
**Flow:**
- On affiche un modal qui explique que la session est expirée et qu'il faut se reconnecter
- Le user clique sur le bouton reconnexion qui le redirige à la page de connexion
- Lorsque la connexion est réussie, on ramène l'utilisateur au même endroit et au même state qu'au moment du timeout
- Si la connexion échoue (ex: mot de passe / username error), alors on suit le flow actuel d'erreur de connexion.

**Maquetes:**
https://www.figma.com/file/jr5tRIgOKZ6nT5HX3Ddp7R/?node-id=212%3A35659

**Comment by kjacqueschu** [comment]
@luclemo En ce moment, si la page reste ouverte, toute la session s'auto-rafraîchi sans aucune interaction de l'utilisateur.
Si le token est expirer et que son refresh token l'est aussi et qu'il revient sur une page qui a besoin d'être authentifié, il est rediriger vers le login page normal. Je crois que cette approche réduit au minimum les frictions possible.
