### ISSUE TITLE
(cqdg-clinical-data-service) Validation des données cliniques via Lectern

### ISSUE THREAD

**Issue by plaplante-lab** [Ferlab-Ste-Justine/cqdg-project#313]
https://docs.google.com/spreadsheets/d/1KMjHqNjLkHntvKRtTXB0c25plwXVc6WzLdW8fxkVxJs/edit?ts=601c5433#gid=1187230549

**Comment by plaplante-chust** [comment]
1. changer les regex pour celles définies par Denis
2. au besoin, ajouter les scripts requis pour les validations plus complexe
3. tester les regex via le cqdg-clinical-data-service.

**Comment by plaplante-chust** [comment]
1. mettre à jour les regexes dans le dictionnaires
2. ajouter les scripts pour les validations plus complexes (là où nécessaire)
3. tester la validation des données via le clinical-data-service.
