### ISSUE TITLE
Les requetes avec les facettes ontologiques ne fonctionnent pas

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/cqdg-project#386]
quand un requete implique un ou des champs ontologiques (CIM, HPO, Mondo)
retourne toujours 0 étude, que ce soit dans File repo ou la page Études

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/978a5a04-0da3-4e55-90b8-f0cdf092af14)

**Comment by adipaul1981** [comment]
should be closed.
covered by: #396 and
