### ISSUE TITLE
la page Etude ne s'affiche plus

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/cqdg-project#393]
https://portal.qa.cqdg.ferlab.bio/study/STU0000001

On obtient une page avec roue qui tourne
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/15a8e55d-68ac-4718-8bcd-0b8399478731)

**Comment by creativeyann17** [comment]
```js
errors: [{,…}]
0: {,…}
extensions: {code: "INTERNAL_SERVER_ERROR", exception: {stacktrace: [,…]}}
locations: [{line: 8, column: 13}]
message: "String cannot represent value: [\"user specific restriction (DUO:0000026)\", \"publication moratorium (DUO:0000024)\", \"data use modifier (DUO:0000017)\"]"
path: ["Study", "hits", "edges", 0, "node", "data_access_codes", "access_requirements"]
```
Common reason for this error => data isn't the same as portal is expected

**Comment by creativeyann17** [comment]
ES QA data update + reboot of cqdg-aranger => test is OK
