### ISSUE TITLE
Requête qui génère 0 donneurs - FILE REPOSITORY

### ISSUE THREAD

**Issue by cboileau-ferlab** [Ferlab-Ste-Justine/cqdg-project#409]
La requête Abnormality of the genitourinary system (HP:0000119) génère 0 donneurs 

![image.png](https://images.zenhubusercontent.com/605ddf41f82f016ee6c21d60/b352fbfa-516e-42da-a4ac-b10e2a3b4eb2)

**Comment by adipaul1981** [comment]
Same issue as #396 - closed
