### ISSUE TITLE
Impossible d'appliquer les filtres "âge au recrutement" et "âge au diagnostic" 

### ISSUE THREAD

**Issue by cboileau-ferlab** [Ferlab-Ste-Justine/cqdg-project#411]
si j’entre des chiffres dans les champs min et max (disons 5 et 9) ça me retourne un page d’erreur 

![image.png](https://images.zenhubusercontent.com/605ddf41f82f016ee6c21d60/cc4c1f2d-59aa-457c-b5a6-83975f912f96)

**Comment by adipaul1981** [comment]
fixed by [#437](https://github.com/ferlab-ste-justine/cqdg-project/issues/437)
