### ISSUE TITLE
Appliquer le style guide sur le Header

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#43]

**Comment by luclemo** [comment]
@YanLabCHU almost there!

**Principal links** (acces, soumettre, etc)
- 2px border radius
- Wrong font size

**Markup**
- Add `lang` attribute to the `html` tag (need this to pass accessibility audit)

**Comment by luclemo** [comment]
The language switcher should also be an ancor link.
