### ISSUE TITLE
Home Page - Point Manquant

### ISSUE THREAD

**Issue by francisl** [Ferlab-Ste-Justine/cqdg-project#66]
### DEFECTS

- [x] Boutons "Répertoire de fichiers" et "Études" dans le header ainsi que "Connexion" et "Créer un compte" en milieu de page, n'ont pas la bonne Police (Voir screenshot)
- [x] Fautes d'orthographe. Les mots "Donneurs" ou "Données" doivent être écrits avec 2 "n". (Voir screenshot)
- [x] Résumé des données (_Hard-coder_ des valeurs plus réalistes et non "3" partout - Voir screenshot)
- [x] Section avec les cartes en bas. Les cartes devraient être moins espacées
- [x] Section avec les cartes en bas. Le texte dans les cartes devrait être moins large et plus centré dans la carte
- [x] Section avec les cartes en bas. La carte du milieu n'a pas le point bleu dedans
- [x] Le background avec les pilules devrait être moins zoomé pour que les pilules plus pâles soient plus petites un peu (voir maquette).

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/64538118/100654961-9c554e00-3318-11eb-8f8d-f18c5a3d0c54.png)

![image](https://user-images.githubusercontent.com/64538118/100656754-2d2d2900-331b-11eb-893e-57f54c5b9adc.png)

![image](https://user-images.githubusercontent.com/64538118/100659895-489a3300-331f-11eb-85c9-9e5c606e77cc.png)

**Comment by kjacqueschu** [comment]
- Finaliser tous les types de boutons pour matcher avec le design
- Utiliser de vrai graphiqe avec du bon data au lieu d'image
- Traduire toute la page

**Comment by denis-crsj** [comment]
@kjacqueschu J'ai fermé les autres cartes du Epic et j'ai centralisé la liste de defects dans celle-ci. Laisse0moi savoir si jamais tu as des questions en lien avecun ou des defects

**Comment by kjacqueschu** [comment]
Pour le logo dans la carte du milieu du bas, dans le design elle n'a déjà pas de point. Si on la veux, il faudrait demander a Lucas de l'ajouter @denis-crsj

**Comment by luclemo** [comment]
@kjacqueschu 
[37_scientific_literature.zip](https://github.com/Ferlab-Ste-Justine/cqdg-project/files/5624843/37_scientific_literature.zip)

**Comment by denis-crsj** [comment]
Tous les defects ont été corigés
