### ISSUE TITLE
Le lien "Accès au portail" au centre de la page devrait pointer à la page d'accueil du Portail

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/cqdg-project#80]
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/d730b780-b8f2-42e1-8691-933f32bd1663)

**Comment by plaplante-chust** [comment]
@denis-crsj @Magnitus-  ceci va nécessiter que le portail soit déployé dans notre infra - à moins qu'on compte continuer d'utiliser la machine sandbox pour héberger la démo? (http://cqdg.ferlab.bio:8080/)

**Comment by denis-crsj** [comment]
@luclemo Le lien redirige maintenant bien sur la page d'accueil du Portail. Toutefois, elle ouvre présentement dans un nouvel onglet. Voulons-nous garder ce comportement ou nous préférerions rester dans le même onglet ?

**Comment by denis-crsj** [comment]
@kjacqueschu Il semble que le lien pointe toujours vers la page d'accueil anglaise du portail. Est-ce un bug ou est-ce seulement à cause de la langue de mon browser qui est en anglais ?

**Comment by kjacqueschu** [comment]
@denis-crsj la page d'accueil va toujours pointé en ce moment sur le / et dans le projet il ya une redirection vers /home. La langue que tu vois est celle de tom browser et n'est pas décidé par ce lien que tu as cliqué :). cela va changer dans le nouveau projet si on decide d'avoir des liens en francais et anglais
